# CREATE A RSA PRIVATE/PUBLIC KEY PAIR WITH NO PASSPHRASE, IN A SPECIFIED 
# DIRECTORY, WITH A DESCRIPTIVE FILE IDENTIFYING THE CONTEXT OF THE KEY PAIR,
# WHILE BEING SENSITIVE TO THE VERBOSITY REQUEST

# ABSOLUTE PATH FOR THE DIRECTORY TO CONTAIN THE NEW FILES
path=$1

# DESCRIPTOR FOR THE CONTEXT OF THE KEY PAIRS
descriptor=$2

# REQUESTED VERBOSITY
verbose=$3

# CREATES THE RSA KEY WITH NO PASSPHRASE IN THE SPECIFIED PATH
if [ $verbose == 'True' ]; then
  ssh-keygen -t rsa -f $1/id_rsa -N ''
else
  ssh-keygen -t rsa -f $1/id_rsa -N '' > /dev/null
fi

# CREATES THE DESCRIPTIVE FILE IDENTIFIER FOR THE KEY-PAIR 
touch $1/id_rsa.key-pair.$2
